# .github/workflows/deploy.yml
name: AWS CodeCommit Mirror with GitHub Actions
on: push
env:
  AWS_REGION: ap-northeast-1
  REPOSITORY_NAME: cmtt
permissions:
  id-token: write
  contents: read
jobs:
  CodeCommitMirror:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository (Checkout)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 #これがない場合、checkout時にエラーが出る。
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::969393671445:role/github-OIDC-Role
          role-session-name: testuserclone
          aws-region: ${{ env.AWS_REGION }}
      - name: Push to CodeCommit (Mirroring)
        run: |
          git config --global credential.helper '!aws codecommit credential-helper $@'
          git config --global credential.UseHttpPath true
          git remote add codecommit https://git-codecommit.${{ env.AWS_REGION }}.amazonaws.com/v1/repos/${{ env.REPOSITORY_NAME }}
          git push --mirror codecommit
